// ─── Seeded Library Content ───────────────────────────────────────────────────
// Master content definitions. These are the source-of-truth templates.
// Never edited by team users — imports create editable copies.

export const SEED_PACKS = [
  // ── OFFENSE ────────────────────────────────────────────────────────────────
  {
    pack_name: 'Youth I-Formation Starter',
    pack_type: 'offense_system',
    side_of_ball: 'offense',
    age_level: 'youth',
    system_family: 'I-Formation',
    description: 'Core I-Formation runs and play-action passes. Ideal for youth teams learning base power football.',
    sort_order: 1,
  },
  {
    pack_name: 'Youth Shotgun Spread Core',
    pack_type: 'offense_system',
    side_of_ball: 'offense',
    age_level: 'youth',
    system_family: 'Spread',
    description: 'Shotgun-based spread concepts. Quick game, RPO shells, and simple zone run game.',
    sort_order: 2,
  },
  {
    pack_name: 'Wing-T Starter Package',
    pack_type: 'offense_system',
    side_of_ball: 'offense',
    age_level: 'youth',
    system_family: 'Wing-T',
    description: 'Classic Wing-T trapping system. Buck sweep, trap, counter, waggle, and play-action.',
    sort_order: 3,
  },
  {
    pack_name: 'Wildcat & Jet Motion Pack',
    pack_type: 'offense_system',
    side_of_ball: 'offense',
    age_level: 'youth',
    system_family: 'Wildcat',
    description: 'Jet sweep motion, Wildcat direct snap, and supplemental speed concepts.',
    sort_order: 4,
  },
  {
    pack_name: 'Red Zone & Goal Line Bundle',
    pack_type: 'situation_bundle',
    side_of_ball: 'offense',
    age_level: 'all',
    system_family: 'Multiple',
    description: 'Condensed field plays: power runs, QB sneaks, bootlegs, and fade routes. Works for any system.',
    sort_order: 5,
  },
  {
    pack_name: '3rd Down & Two-Minute Plays',
    pack_type: 'situation_bundle',
    side_of_ball: 'offense',
    age_level: 'all',
    system_family: 'Multiple',
    description: '3rd & short, 3rd & medium, and 2-minute drive concepts.',
    sort_order: 6,
  },
  {
    pack_name: 'Formation Templates (Offense)',
    pack_type: 'formation_pack',
    side_of_ball: 'offense',
    age_level: 'all',
    system_family: 'Multiple',
    description: 'Reusable pre-snap formation snapshots: Pro, I, Shotgun 2x2, Trips, Bunch, Empty.',
    sort_order: 7,
  },
  // ── DEFENSE ────────────────────────────────────────────────────────────────
  {
    pack_name: 'Youth 6-2 Defense Starter',
    pack_type: 'defense_system',
    side_of_ball: 'defense',
    age_level: 'youth',
    system_family: '6-2',
    description: '6-2 base defense for youth football. Run fits, pursuit angles, and simple zone coverage.',
    sort_order: 10,
  },
  {
    pack_name: '5-3 Defense Package',
    pack_type: 'defense_system',
    side_of_ball: 'defense',
    age_level: 'youth',
    system_family: '5-3',
    description: '5-3 base with built-in gap integrity. Gap assignments, contain, and short zone drops.',
    sort_order: 11,
  },
  {
    pack_name: '4-4 Defense & Pressure Package',
    pack_type: 'defense_system',
    side_of_ball: 'defense',
    age_level: 'middle_school',
    system_family: '4-4',
    description: '4-4 base defense with linebacker blitz packages and zone coverage shells.',
    sort_order: 12,
  },
  {
    pack_name: 'Defensive Red Zone Package',
    pack_type: 'situation_bundle',
    side_of_ball: 'defense',
    age_level: 'all',
    system_family: 'Multiple',
    description: 'Goal line defense, inside-out fits, and condensed zone coverage in the red zone.',
    sort_order: 13,
  },
  // ── SPECIAL TEAMS ─────────────────────────────────────────────────────────
  {
    pack_name: 'Special Teams Starter Pack',
    pack_type: 'special_teams',
    side_of_ball: 'special_teams',
    age_level: 'youth',
    system_family: 'Multiple',
    description: 'Kickoff, kickoff return, punt, punt return, PAT/FG. Core youth special teams units.',
    sort_order: 20,
  },
];

export const SEED_ITEMS = [
  // ─ I-Formation plays ──────────────────────────────────────────────────────
  {
    item_name: 'ISO Right',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'I-Formation',
    formation_name: 'I-Formation',
    concept_family: 'ISO',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Fullback blocks MIKE, tailback follows to the right A or B gap.',
    coaching_points: 'FB takes on MIKE linebacker. TB reads the block and hits the open gap.',
    situation_tags: ['base', 'openers', '1st_down'],
    starter_recommended: true,
    sort_order: 1,
    play_data: {
      name: 'ISO Right', short_name: 'ISO R', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'ISO', formation: 'I-Formation', concept: 'ISO', direction: 'right',
      risk_level: 'low', age_level_difficulty: 'youth',
      coaching_points: 'FB takes on MIKE linebacker. TB reads the block and hits the open gap.',
      down_distance_tags: ['1st-10', '2nd-short', '2nd-medium'],
      field_zone_tags: ['own_territory', 'midfield'],
    },
  },
  {
    item_name: 'Power Right',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'I-Formation',
    formation_name: 'I-Formation',
    concept_family: 'Power',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Guard pulls to lead through the C gap. TE kicks out the end.',
    coaching_points: 'Guard must clear the line and lead into the hole. TB follows the pull.',
    situation_tags: ['openers', 'short_yardage', 'goal_line'],
    starter_recommended: true,
    sort_order: 2,
    play_data: {
      name: 'Power Right', short_name: 'PWR R', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Power', formation: 'I-Formation', concept: 'Power', direction: 'right',
      risk_level: 'low', age_level_difficulty: 'youth',
      coaching_points: 'Guard must clear the line and lead into the hole. TB follows the pull.',
      down_distance_tags: ['1st-10', '2nd-short', '3rd-short', 'goal_line'],
      field_zone_tags: ['own_territory', 'midfield', 'red_zone', 'goal_line'],
    },
  },
  {
    item_name: 'Counter Trey',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'I-Formation',
    formation_name: 'I-Formation',
    concept_family: 'Counter',
    run_pass: 'run',
    difficulty_level: 'intermediate',
    age_level: 'youth',
    short_description: 'Backfield misdirection with double-pull. Back takes a jab step away before hitting the counter gap.',
    coaching_points: 'Sell the counter step. Guard and tackle pull. Hit the B gap off the pulling linemen.',
    situation_tags: ['base', 'openers'],
    starter_recommended: true,
    sort_order: 3,
    play_data: {
      name: 'Counter Trey', short_name: 'CTR', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Counter', formation: 'I-Formation', concept: 'Counter Trey', direction: 'right',
      risk_level: 'medium', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Play Action Boot',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'I-Formation',
    formation_name: 'I-Formation',
    concept_family: 'Play Action',
    run_pass: 'pass',
    difficulty_level: 'intermediate',
    age_level: 'youth',
    short_description: 'Power fake, QB boots opposite. TE crosses, FB flares, backside WR clears.',
    coaching_points: 'Sell the power fake hard. QB reads the TE cross first, FB flat second.',
    situation_tags: ['openers', 'shot_plays'],
    starter_recommended: true,
    sort_order: 4,
    play_data: {
      name: 'Play Action Boot Left', short_name: 'PA BOOT', side: 'offense', run_pass: 'pass', play_type: 'play_action',
      play_family: 'Play Action', formation: 'I-Formation', concept: 'Bootleg', direction: 'left',
      risk_level: 'medium', age_level_difficulty: 'youth',
    },
  },
  // ─ Spread plays ─────────────────────────────────────────────────────────────
  {
    item_name: 'Inside Zone',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Spread',
    formation_name: 'Shotgun 2x2',
    concept_family: 'Inside Zone',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Zone-blocked run with RB reading front-side linebacker.',
    coaching_points: 'OL zone steps to the playside. RB aims for front-side A gap and reads the MIKE.',
    situation_tags: ['base', 'openers', '1st_down'],
    starter_recommended: true,
    sort_order: 10,
    play_data: {
      name: 'Inside Zone', short_name: 'IZ', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Zone', formation: 'Shotgun 2x2', concept: 'Inside Zone', direction: 'any',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Slant-Flat',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Spread',
    formation_name: 'Shotgun 2x2',
    concept_family: 'Slant',
    run_pass: 'pass',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Outside WR slants inside, inside slot runs a flat route. QB reads WILL linebacker.',
    coaching_points: 'Quick rhythm throw. Read WILL LB: drops inside = throw flat, stays = slant.',
    situation_tags: ['base', '3rd_short', 'two_minute'],
    starter_recommended: true,
    sort_order: 11,
    play_data: {
      name: 'Slant Flat', short_name: 'SLT-FL', side: 'offense', run_pass: 'pass', play_type: 'pass',
      play_family: 'Quick Game', formation: 'Shotgun 2x2', concept: 'Slant Flat', direction: 'any',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Mesh Concept',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Spread',
    formation_name: 'Shotgun Trips',
    concept_family: 'Mesh',
    run_pass: 'pass',
    difficulty_level: 'intermediate',
    age_level: 'middle_school',
    short_description: 'Two crossing routes rub defenders. High-low with a seam or wheel.',
    coaching_points: 'Crossers skim the LOS. QB reads the shallow cross vs coverage rotation.',
    situation_tags: ['base', '3rd_medium', 'shot_plays'],
    starter_recommended: true,
    sort_order: 12,
    play_data: {
      name: 'Mesh', short_name: 'MESH', side: 'offense', run_pass: 'pass', play_type: 'pass',
      play_family: 'Mesh', formation: 'Shotgun Trips', concept: 'Mesh', direction: 'any',
      risk_level: 'medium', age_level_difficulty: 'middle_school',
    },
  },
  // ─ Wing-T plays ──────────────────────────────────────────────────────────────
  {
    item_name: 'Buck Sweep',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Wing-T',
    formation_name: 'Wing-T',
    concept_family: 'Sweep',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Both guards pull to lead the ball carrier around the edge.',
    coaching_points: 'Guards pull flat down the LOS. Wing kicks out the end. Back follows the guards.',
    situation_tags: ['openers', 'base', '1st_down'],
    starter_recommended: true,
    sort_order: 20,
    play_data: {
      name: 'Buck Sweep Right', short_name: 'BUCK R', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Sweep', formation: 'Wing-T', concept: 'Buck Sweep', direction: 'right',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Belly Trap',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Wing-T',
    formation_name: 'Wing-T',
    concept_family: 'Trap',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Offside guard traps the penetrating DT. Complement to sweep.',
    coaching_points: 'Let the DT penetrate. Guard traps inside out. HB hits the A gap.',
    situation_tags: ['base', 'openers'],
    starter_recommended: false,
    sort_order: 21,
    play_data: {
      name: 'Belly Trap', short_name: 'TRAP', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Trap', formation: 'Wing-T', concept: 'Belly Trap', direction: 'any',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Waggle Pass',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Wing-T',
    formation_name: 'Wing-T',
    concept_family: 'Play Action',
    run_pass: 'pass',
    difficulty_level: 'intermediate',
    age_level: 'youth',
    short_description: 'Sweep action fake, QB rolls to run or pass. Classic Wing-T misdirection pass.',
    coaching_points: 'Make the sweep fake convincing. QB rolls, reads flat then crossing route.',
    situation_tags: ['openers', 'shot_plays'],
    starter_recommended: true,
    sort_order: 22,
    play_data: {
      name: 'Waggle Right', short_name: 'WAG R', side: 'offense', run_pass: 'pass', play_type: 'play_action',
      play_family: 'Play Action', formation: 'Wing-T', concept: 'Waggle', direction: 'right',
      risk_level: 'medium', age_level_difficulty: 'youth',
    },
  },
  // ─ Red Zone & Special Situations ─────────────────────────────────────────────
  {
    item_name: 'QB Sneak',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Multiple',
    formation_name: 'Under Center',
    concept_family: 'Sneak',
    run_pass: 'run',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'QB sneaks behind the center. Used for short yardage and goal line.',
    coaching_points: 'OL drives on snap. QB falls forward immediately between center legs.',
    situation_tags: ['goal_line', 'short_yardage', '3rd_short'],
    starter_recommended: true,
    sort_order: 30,
    play_data: {
      name: 'QB Sneak', short_name: 'SNEAK', side: 'offense', run_pass: 'run', play_type: 'run',
      play_family: 'Sneak', formation: 'Under Center', concept: 'QB Sneak', direction: 'middle',
      risk_level: 'low', age_level_difficulty: 'youth',
      down_distance_tags: ['3rd-short', 'goal_line', '2pt'],
      field_zone_tags: ['goal_line', 'red_zone'],
    },
  },
  {
    item_name: 'Fade to Corner',
    item_type: 'play',
    side_of_ball: 'offense',
    system_family: 'Multiple',
    formation_name: 'Trips Right',
    concept_family: 'Fade',
    run_pass: 'pass',
    difficulty_level: 'intermediate',
    age_level: 'youth',
    short_description: 'Back-shoulder fade to the boundary or back-of-end-zone corner. Red zone shot play.',
    coaching_points: 'WR sells inside release, fades to back pylon. QB throws to the shoulder away from the defender.',
    situation_tags: ['red_zone', 'goal_line', 'shot_plays'],
    starter_recommended: true,
    sort_order: 31,
    play_data: {
      name: 'Fade Right', short_name: 'FADE R', side: 'offense', run_pass: 'pass', play_type: 'pass',
      play_family: 'Fade', formation: 'Trips Right', concept: 'Fade', direction: 'right',
      risk_level: 'medium', age_level_difficulty: 'youth',
      field_zone_tags: ['red_zone', 'goal_line'],
    },
  },
  // ─ Defense ─────────────────────────────────────────────────────────────────
  {
    item_name: '6-2 Base Defense',
    item_type: 'defensive_look',
    side_of_ball: 'defense',
    system_family: '6-2',
    formation_name: '6-2',
    concept_family: 'Base',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Six man front with two linebackers filling run gaps. Simple gap-sound run defense.',
    coaching_points: 'Each defender owns their gap. LBs scrape to the ball. CB play outside contain.',
    situation_tags: ['base', 'openers'],
    starter_recommended: true,
    sort_order: 50,
    play_data: {
      name: '6-2 Base', short_name: '6-2', side: 'defense', run_pass: 'n/a', play_type: 'run',
      play_family: '6-2', formation: '6-2', concept: 'Base 6-2',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: '5-3 Base Defense',
    item_type: 'defensive_look',
    side_of_ball: 'defense',
    system_family: '5-3',
    formation_name: '5-3',
    concept_family: 'Base',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Five man front, three linebackers. Solid gap control with flexible zone drops.',
    coaching_points: 'Nose owns both A gaps. Ends contain. LBs fill and scrape based on flow.',
    situation_tags: ['base', 'openers'],
    starter_recommended: true,
    sort_order: 51,
    play_data: {
      name: '5-3 Base', short_name: '5-3', side: 'defense', run_pass: 'n/a', play_type: 'run',
      play_family: '5-3', formation: '5-3', concept: 'Base 5-3',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'LB Blitz Package',
    item_type: 'defensive_look',
    side_of_ball: 'defense',
    system_family: '5-3',
    formation_name: '5-3',
    concept_family: 'Pressure',
    difficulty_level: 'intermediate',
    age_level: 'youth',
    short_description: 'Inside linebacker blitz with zone coverage behind. Creates confusion and pressure.',
    coaching_points: 'MIKE and WILL shoot the A and B gaps. CBs rotate to cover vacated zones.',
    situation_tags: ['3rd_long', 'pressure', 'two_minute'],
    starter_recommended: false,
    sort_order: 52,
    play_data: {
      name: 'MIKE WILL Blitz', short_name: 'MW BLTZ', side: 'defense', run_pass: 'n/a', play_type: 'pass',
      play_family: 'Pressure', formation: '5-3', concept: 'LB Blitz',
      risk_level: 'high', age_level_difficulty: 'youth',
    },
  },
  // ─ Formation templates ─────────────────────────────────────────────────────
  {
    item_name: 'Shotgun 2x2 Formation',
    item_type: 'formation_template',
    side_of_ball: 'offense',
    system_family: 'Spread',
    formation_name: 'Shotgun 2x2',
    concept_family: 'Formation',
    difficulty_level: 'beginner',
    age_level: 'all',
    short_description: '5-man protection, 2 receivers to each side, QB in shotgun.',
    starter_recommended: true,
    sort_order: 60,
  },
  {
    item_name: 'I-Formation Pro',
    item_type: 'formation_template',
    side_of_ball: 'offense',
    system_family: 'I-Formation',
    formation_name: 'I-Formation Pro',
    concept_family: 'Formation',
    difficulty_level: 'beginner',
    age_level: 'all',
    short_description: 'Standard I-Formation with split end and flanker. Best all-purpose youth formation.',
    starter_recommended: true,
    sort_order: 61,
  },
  {
    item_name: 'Trips Right',
    item_type: 'formation_template',
    side_of_ball: 'offense',
    system_family: 'Spread',
    formation_name: 'Shotgun Trips Right',
    concept_family: 'Formation',
    difficulty_level: 'beginner',
    age_level: 'all',
    short_description: '3 receivers strong side, 1 back. Overloads one side of defense.',
    starter_recommended: false,
    sort_order: 62,
  },
  // ─ Special Teams ──────────────────────────────────────────────────────────
  {
    item_name: 'Kickoff Coverage',
    item_type: 'special_teams_unit',
    side_of_ball: 'special_teams',
    system_family: 'Multiple',
    concept_family: 'Kickoff',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Standard lanes coverage kickoff. Players maintain lane discipline to contain return.',
    coaching_points: 'Run your lane. Do not cross. Converge on ball carrier only inside your lane.',
    situation_tags: ['kickoff'],
    starter_recommended: true,
    sort_order: 70,
    play_data: {
      name: 'Kickoff Coverage', short_name: 'KO COV', side: 'special_teams', run_pass: 'special_teams', play_type: 'special_teams',
      play_family: 'Kickoff', concept: 'Kickoff Coverage',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
  {
    item_name: 'Punt Team Base',
    item_type: 'special_teams_unit',
    side_of_ball: 'special_teams',
    system_family: 'Multiple',
    concept_family: 'Punt',
    difficulty_level: 'beginner',
    age_level: 'youth',
    short_description: 'Base punt formation with gunners and personal protector.',
    coaching_points: 'Protection first. Gunners release on snap and stay outside shoulders of blockers.',
    situation_tags: ['punt'],
    starter_recommended: true,
    sort_order: 71,
    play_data: {
      name: 'Punt Base', short_name: 'PUNT', side: 'special_teams', run_pass: 'special_teams', play_type: 'special_teams',
      play_family: 'Punt', concept: 'Base Punt',
      risk_level: 'low', age_level_difficulty: 'youth',
    },
  },
];

export const SEED_BUNDLES = [
  {
    bundle_name: 'Day 1 Install — Offense',
    bundle_type: 'install_day',
    side_of_ball: 'offense',
    description: 'Core base runs and quick passes to install on Day 1. Every system needs these.',
    situation_key: 'openers',
    age_level: 'youth',
    sort_order: 1,
  },
  {
    bundle_name: 'Red Zone Package',
    bundle_type: 'situation',
    side_of_ball: 'offense',
    description: 'High-percentage plays inside the 20. Power runs, fades, and quick passes.',
    situation_key: 'red_zone',
    age_level: 'all',
    sort_order: 2,
  },
  {
    bundle_name: '3rd & Short Conversion',
    bundle_type: 'situation',
    side_of_ball: 'offense',
    description: 'Short-yardage conversions: QB sneak, power, ISO, and quick slants.',
    situation_key: 'third_short',
    age_level: 'all',
    sort_order: 3,
  },
  {
    bundle_name: 'Goal Line Offense',
    bundle_type: 'situation',
    side_of_ball: 'offense',
    description: 'Inside the 5-yard line plays: sneaks, powers, and fade routes.',
    situation_key: 'goal_line',
    age_level: 'all',
    sort_order: 4,
  },
  {
    bundle_name: 'Shot Plays & Big Play Package',
    bundle_type: 'situation',
    side_of_ball: 'offense',
    description: 'Deep routes, boots, and play-action passes designed to create explosive gains.',
    situation_key: 'shot_plays',
    age_level: 'all',
    sort_order: 5,
  },
  {
    bundle_name: 'Day 1 Install — Defense',
    bundle_type: 'install_day',
    side_of_ball: 'defense',
    description: 'Base defensive front, coverage shells, and pursuit angles.',
    situation_key: 'def_base',
    age_level: 'youth',
    sort_order: 10,
  },
  {
    bundle_name: 'Defensive Red Zone Package',
    bundle_type: 'situation',
    side_of_ball: 'defense',
    description: 'Goal line defense and condensed zone concepts for inside the 20.',
    situation_key: 'def_red_zone',
    age_level: 'all',
    sort_order: 11,
  },
  {
    bundle_name: 'Special Teams Essentials',
    bundle_type: 'install_day',
    side_of_ball: 'special_teams',
    description: 'Kickoff, punt, and PAT units. The minimum viable special teams package.',
    situation_key: 'st_kickoff',
    age_level: 'youth',
    sort_order: 20,
  },
];