export const seedFormations = [
  {
    id: 'doubles',
    name: 'Doubles',
    family: '2x2',
    personnel: ['10', '11'],
    notes: 'Balanced 2x2 spread set.',
  },
  {
    id: 'doubles-nasty',
    name: 'Doubles Nasty',
    family: 'compressed',
    personnel: ['10', '11'],
    notes: 'Reduced split variation to tighten support rules and change leverage.',
  },
  {
    id: 'trips',
    name: 'Trips',
    family: '3x1',
    personnel: ['10', '11'],
    notes: 'Standard 3x1 set for access throws, spacing, and coverage identification.',
  },
  {
    id: 'trips-open',
    name: 'Trips Open',
    family: '3x1',
    personnel: ['10', '11'],
    notes: '3x1 with detached spacing for horizontal stress.',
  },
  {
    id: 'bunch',
    name: 'Bunch',
    family: 'compressed',
    personnel: ['10', '11'],
    notes: 'Tight cluster for releases, picks, and condensed spacing.',
  },
  {
    id: 'snug',
    name: 'Snug',
    family: 'tight',
    personnel: ['10', '11', '12'],
    notes: 'Condensed formation family that keeps assignments stable while changing presentation.',
  },
  {
    id: 'pistol-strong',
    name: 'Pistol Strong',
    family: 'pistol',
    personnel: ['11', '12', '20'],
    notes: 'Pistol presentation for downhill runs and play-action.',
  },
  {
    id: 'empty',
    name: 'Empty',
    family: 'empty',
    personnel: ['empty', '10', '11'],
    notes: 'Open spacing for quick game and pressure identification.',
  },
];

export const seedTags = [
  {
    id: 'tag-jet',
    name: 'Jet',
    kind: 'motion',
    appliesTo: ['run', 'quick', 'screen', 'play_action'],
    notes: 'Fast motion to create edge conflict and eye candy.',
  },
  {
    id: 'tag-orbit',
    name: 'Orbit',
    kind: 'motion',
    appliesTo: ['run', 'quick', 'screen', 'play_action'],
    notes: 'Return motion for perimeter stress and counter presentation.',
  },
  {
    id: 'tag-trade',
    name: 'Trade',
    kind: 'formation',
    appliesTo: ['run', 'quick', 'dropback', 'screen', 'play_action'],
    notes: 'Shift strength without changing core concept.',
  },
  {
    id: 'tag-slice',
    name: 'Slice',
    kind: 'run',
    appliesTo: ['run', 'play_action'],
    notes: 'Split-flow action across zone run structure.',
  },
  {
    id: 'tag-read',
    name: 'Read',
    kind: 'rpo',
    appliesTo: ['run', 'play_action'],
    notes: 'Attach a conflict read to the base run.',
  },
  {
    id: 'tag-bubble',
    name: 'Bubble',
    kind: 'screen',
    appliesTo: ['run', 'quick', 'screen'],
    notes: 'Perimeter access attached to a base concept.',
  },
  {
    id: 'tag-now',
    name: 'Now',
    kind: 'screen',
    appliesTo: ['quick', 'screen'],
    notes: 'Fast perimeter throw when leverage is soft.',
  },
  {
    id: 'tag-arc',
    name: 'Arc',
    kind: 'run',
    appliesTo: ['run', 'play_action'],
    notes: 'Arc release to change who gets accounted for on the edge.',
  },
  {
    id: 'tag-wheel',
    name: 'Wheel',
    kind: 'pass',
    appliesTo: ['quick', 'dropback', 'play_action'],
    notes: 'Vertical outlet or matchup tag off a base concept.',
  },
  {
    id: 'tag-bender',
    name: 'Bender',
    kind: 'pass',
    appliesTo: ['dropback'],
    notes: 'Inside vertical adjustment versus middle-open looks.',
  },
  {
    id: 'tag-switch',
    name: 'Switch',
    kind: 'pass',
    appliesTo: ['dropback', 'special'],
    notes: 'Release change to stress match and leverage rules.',
  },
  {
    id: 'tag-half-slide',
    name: 'Half Slide',
    kind: 'protection',
    appliesTo: ['dropback', 'play_action'],
    notes: 'Base pass protection family.',
  },
];

export const seedConcepts = [
  {
    id: 'inside-zone',
    name: 'Inside Zone',
    family: 'run',
    description: 'Core downhill zone run that can carry reads, split flow, and perimeter attachments.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Trips Open', 'Pistol Strong', 'Snug'],
    motions: ['Jet', 'Orbit', 'Trade'],
    tags: ['Read', 'Slice', 'Arc', 'Bubble'],
    situations: ['base', 'first_and_ten', 'second_medium', 'backed_up', 'red_zone'],
    bestVs: ['Even box', 'Light box', 'Fast overhang support'],
    complements: ['Stick', 'Bubble', 'Boot Flood', 'GT Counter'],
    teachingPoints: [
      'Press the front side track and force the box to declare.',
      'Build double teams and climb with clear linebacker fits.',
      'Pair with simple perimeter conflict answers.',
    ],
  },
  {
    id: 'outside-zone',
    name: 'Outside Zone',
    family: 'run',
    description: 'Horizontal stretch run to widen the box and force pursuit discipline.',
    installTier: 2,
    core: true,
    formations: ['Doubles', 'Trips', 'Pistol Strong', 'Snug'],
    motions: ['Jet', 'Orbit'],
    tags: ['Read', 'Bubble', 'Slice'],
    situations: ['base', 'first_and_ten', 'second_short', 'backed_up'],
    bestVs: ['Heavy interior box', 'Slow force', 'Reduced edge setting'],
    complements: ['Boot Flood', 'Bubble', 'Counter', 'Sail'],
    teachingPoints: [
      'Stretch the defense horizontally before cutting vertical.',
      'Landmarks and leverage are more important than speed alone.',
      'Keep the perimeter support player in conflict.',
    ],
  },
  {
    id: 'gt-counter',
    name: 'GT Counter',
    family: 'run',
    description: 'Gap-scheme misdirection run with pullers and strong complement value.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Pistol Strong', 'Snug'],
    motions: ['Jet', 'Orbit', 'Trade'],
    tags: ['Read', 'Bubble', 'Arc'],
    situations: ['base', 'first_and_ten', 'third_short', 'red_zone', 'shot'],
    bestVs: ['Fast flow linebackers', 'Odd front', 'Aggressive edge support'],
    complements: ['Counter Pass', 'Power Read', 'Bubble', '4 Verts'],
    teachingPoints: [
      'Sell the initial picture and hit opposite flow.',
      'Puller path and kick/wrap clarity make the play go.',
      'Use after the defense starts overplaying zone action.',
    ],
  },
  {
    id: 'power-read',
    name: 'Power Read',
    family: 'run',
    description: 'Read-based gap run that forces the edge defender to be wrong.',
    installTier: 2,
    core: false,
    formations: ['Doubles', 'Trips', 'Pistol Strong'],
    motions: ['Jet'],
    tags: ['Read', 'Arc'],
    situations: ['base', 'first_and_ten', 'second_short', 'goal_line'],
    bestVs: ['Overhang conflict', 'Wide edge defender', 'Aggressive scrape fit'],
    complements: ['Inside Zone', 'Jet Sweep Action', 'Counter'],
    teachingPoints: [
      'The read player determines whether the ball hits inside or outside.',
      'Backfield timing and mesh discipline are critical.',
      'Best used when edge defenders are cheating the box fit.',
    ],
  },
  {
    id: 'stick',
    name: 'Stick',
    family: 'quick',
    description: 'Fast completion concept that attacks underneath zone leverage and soft corners.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Trips Open', 'Empty'],
    motions: ['Trade', 'Jet'],
    tags: ['Now', 'Bubble', 'Wheel'],
    situations: ['base', 'first_and_ten', 'second_short', 'third_short', 'red_zone'],
    bestVs: ['Underneath zone', 'Soft apex', 'Cushion'],
    complements: ['Inside Zone', 'Snag', 'Stick Nod'],
    teachingPoints: [
      'Quarterback keys the flat defender first.',
      'Stick route depth and timing must stay consistent.',
      'Great first-down rhythm throw and low-cost install.',
    ],
  },
  {
    id: 'slant-arrow',
    name: 'Slant Arrow',
    family: 'quick',
    description: 'Quick game concept that puts the corner and apex in conflict immediately.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Empty'],
    motions: ['Trade', 'Jet'],
    tags: ['Now', 'Bubble'],
    situations: ['base', 'first_and_ten', 'second_short', 'third_short', 'pressure'],
    bestVs: ['Soft corner', 'Off leverage', 'Pressure access'],
    complements: ['Stick', 'Bubble / Tunnel', 'Inside Zone'],
    teachingPoints: [
      'Create a fast answer when the defense gives free grass.',
      'Slant spacing must not crowd the arrow outlet.',
      'Use as an easy rhythm completion when pressure threatens.',
    ],
  },
  {
    id: 'hitch',
    name: 'Hitch',
    family: 'quick',
    description: 'Simple perimeter completion that punishes cushion and protects the QB.',
    installTier: 1,
    core: false,
    formations: ['Doubles', 'Trips', 'Empty'],
    motions: ['Trade'],
    tags: ['Now'],
    situations: ['base', 'first_and_ten', 'backed_up', 'pressure'],
    bestVs: ['Soft corners', 'Bail technique', 'Off-man'],
    complements: ['Fade Out', 'Slant Arrow', 'Quick Screen'],
    teachingPoints: [
      'Take cheap access yards without overcomplicating the picture.',
      'Receivers must attack the defender before snapping down.',
      'Best when the defense is protecting over the top.',
    ],
  },
  {
    id: 'snag',
    name: 'Snag',
    family: 'quick',
    description: 'Triangle quick concept that creates a high-low on the curl/flat area.',
    installTier: 2,
    core: true,
    formations: ['Doubles', 'Trips', 'Bunch', 'Snug'],
    motions: ['Trade'],
    tags: ['Wheel'],
    situations: ['first_and_ten', 'second_medium', 'third_short', 'red_zone'],
    bestVs: ['Zone flat defender', 'Corner squat technique', 'Red zone spacing'],
    complements: ['Stick', 'Sail', 'Mesh'],
    teachingPoints: [
      'Space the corner, snag, and flat routes cleanly.',
      'Excellent in condensed spaces because the read stays defined.',
      'Fits well off the same fast-game picture as Stick.',
    ],
  },
  {
    id: 'mesh',
    name: 'Mesh',
    family: 'dropback',
    description: 'Horizontal crossing concept with answers versus both man and zone.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Bunch', 'Snug'],
    motions: ['Trade', 'Jet'],
    tags: ['Wheel', 'Switch'],
    situations: ['second_medium', 'third_medium', 'two_minute', 'red_zone'],
    bestVs: ['Man coverage', 'Pressure man', 'Match coverage'],
    complements: ['Cross', 'Snag', 'Drive'],
    teachingPoints: [
      'Crossers must stay tight and at matched depth.',
      'Settles and run-after-catch rules give the concept flexibility.',
      'This is a true chain-moving answer on known passing downs.',
    ],
  },
  {
    id: 'four-verts',
    name: '4 Verts',
    family: 'dropback',
    description: 'Vertical stress concept that attacks safeties and open grass downfield.',
    installTier: 1,
    core: true,
    formations: ['Doubles', 'Trips', 'Trips Open', 'Empty'],
    motions: ['Trade'],
    tags: ['Bender', 'Switch'],
    situations: ['shot', 'first_and_ten', 'third_long', 'two_minute'],
    bestVs: ['Middle-open looks', 'Aggressive safeties', 'Quarters spacing'],
    complements: ['Stick', 'Sail', 'Inside Zone'],
    teachingPoints: [
      'Quarterback starts with safety structure and leverage.',
      'All receivers must understand spacing versus open and closed middle.',
      'Best when paired with enough underneath game to force safety hesitation.',
    ],
  },
  {
    id: 'cross',
    name: 'Y Cross',
    family: 'dropback',
    description: 'Intermediate concept that isolates safeties and creates strong 3rd-down answers.',
    installTier: 2,
    core: true,
    formations: ['Trips', 'Trips Open', 'Bunch'],
    motions: ['Trade'],
    tags: ['Wheel', 'Half Slide'],
    situations: ['second_long', 'third_medium', 'third_long', 'two_minute'],
    bestVs: ['Single-high', 'Match coverage', 'Aggressive hook players'],
    complements: ['Mesh', 'Sail', 'Dig'],
    teachingPoints: [
      'Cross route depth and landmark are non-negotiable.',
      'Protect the concept well enough to let the route develop.',
      'Excellent when linebackers overplay shallow action.',
    ],
  },
  {
    id: 'sail',
    name: 'Sail',
    family: 'dropback',
    description: 'Flood concept that stretches a sideline defender at multiple depths.',
    installTier: 2,
    core: true,
    formations: ['Trips', 'Doubles', 'Snug', 'Pistol Strong'],
    motions: ['Trade', 'Jet'],
    tags: ['Half Slide', 'Wheel'],
    situations: ['first_and_ten', 'second_medium', 'third_medium', 'shot'],
    bestVs: ['Cover 3', 'Quarter-quarter-half', 'Rolling safeties'],
    complements: ['Boot Flood', 'Smash', '4 Verts'],
    teachingPoints: [
      'Create clear three-level spacing to one sideline.',
      'The underneath control defender must be put in conflict.',
      'Play-action versions make the same picture more explosive.',
    ],
  },
  {
    id: 'smash',
    name: 'Smash',
    family: 'dropback',
    description: 'Classic corner-hitch spacing concept for cover-2 and red-zone stress.',
    installTier: 2,
    core: false,
    formations: ['Doubles', 'Trips', 'Bunch'],
    motions: ['Trade'],
    tags: ['Corner', 'Now'],
    situations: ['first_and_ten', 'third_short', 'red_zone'],
    bestVs: ['Cloud corner', 'Cover 2', 'Squat technique'],
    complements: ['Stick', 'Snag', 'Sail'],
    teachingPoints: [
      'Corner route width and hitch timing must fit together.',
      'The concept is simple, but spacing makes or breaks it.',
      'Good change-up when corners trap fast game.',
    ],
  },
  {
    id: 'dig-mills',
    name: 'Dig / Mills',
    family: 'dropback',
    description: 'Intermediate/deep concept family to attack the post safety and void windows.',
    installTier: 3,
    core: false,
    formations: ['Doubles', 'Trips'],
    motions: ['Trade'],
    tags: ['Bender', 'Half Slide'],
    situations: ['second_long', 'third_long', 'shot'],
    bestVs: ['Single-high safety', 'Aggressive spin safety', 'Match quarters'],
    complements: ['4 Verts', 'Cross', 'Post Wheel'],
    teachingPoints: [
      'Protection and quarterback eyes must hold the middle safety.',
      'Use when you want a more aggressive in-breaker than Cross.',
      'Not a heavy-volume install for every week.',
    ],
  },
  {
    id: 'bubble-tunnel',
    name: 'Bubble / Tunnel',
    family: 'screen',
    description: 'Perimeter screen family that steals grass and punishes numbers leverage.',
    installTier: 1,
    core: true,
    formations: ['Trips', 'Trips Open', 'Doubles', 'Empty'],
    motions: ['Jet', 'Orbit'],
    tags: ['Bubble', 'Now'],
    situations: ['base', 'first_and_ten', 'backed_up', 'pressure'],
    bestVs: ['Off coverage', 'Soft apex', 'Overloaded box'],
    complements: ['Inside Zone', 'Stick', 'GT Counter'],
    teachingPoints: [
      'Get the ball out fast and let leverage do the work.',
      'Block structure must be consistent and easy to teach.',
      'Excellent attachment to the core run menu.',
    ],
  },
  {
    id: 'middle-screen',
    name: 'Middle Screen',
    family: 'screen',
    description: 'Inside screen answer to aggressive rush and interior upfield charge.',
    installTier: 2,
    core: false,
    formations: ['Trips', 'Doubles', 'Pistol Strong'],
    motions: ['Trade'],
    tags: ['Half Slide'],
    situations: ['second_long', 'third_long', 'pressure', 'two_minute'],
    bestVs: ['Interior pressure', 'Wide rush lanes', 'Aggressive twist game'],
    complements: ['4 Verts', 'Mesh', 'Cross'],
    teachingPoints: [
      'Sell pass long enough to invite rush without losing structure.',
      'Timing and release discipline matter more than pure speed.',
      'Useful as a change-up when protections get stressed.',
    ],
  },
  {
    id: 'shuffle-screen',
    name: 'Shuffle Screen',
    family: 'screen',
    description: 'Back-side screen answer that punishes edge rush and pursuit flow.',
    installTier: 2,
    core: false,
    formations: ['Trips', 'Doubles', 'Pistol Strong'],
    motions: ['Orbit'],
    tags: ['Half Slide'],
    situations: ['second_long', 'third_long', 'pressure'],
    bestVs: ['Edge pressure', 'Fast defensive end', 'Wide rush lanes'],
    complements: ['GT Counter', 'Cross', 'Sail'],
    teachingPoints: [
      'Use defensive speed against itself.',
      'Quarterback mechanics must clearly sell the primary dropback picture.',
      'Best after the rush starts chasing launch points aggressively.',
    ],
  },
  {
    id: 'boot-flood',
    name: 'Boot Flood',
    family: 'play_action',
    description: 'Play-action movement concept paired off zone action to stress the edge and flat.',
    installTier: 2,
    core: true,
    formations: ['Doubles', 'Trips', 'Pistol Strong', 'Snug'],
    motions: ['Jet', 'Orbit'],
    tags: ['Slice', 'Half Slide'],
    situations: ['first_and_ten', 'second_short', 'shot', 'red_zone'],
    bestVs: ['Flowing linebackers', 'Overcommitted run support', 'Flat conflict defenders'],
    complements: ['Inside Zone', 'Outside Zone', 'Sail'],
    teachingPoints: [
      'Sell the run picture before escaping the pocket.',
      'Route depth must create an immediate, intermediate, and late outlet.',
      'Excellent shot-control balance off the run menu.',
    ],
  },
  {
    id: 'counter-pass',
    name: 'Counter Pass',
    family: 'play_action',
    description: 'Misdirection shot or intermediate throw off the counter action family.',
    installTier: 3,
    core: false,
    formations: ['Doubles', 'Trips', 'Pistol Strong'],
    motions: ['Jet', 'Trade'],
    tags: ['Half Slide', 'Wheel'],
    situations: ['shot', 'first_and_ten', 'red_zone'],
    bestVs: ['Aggressive second-level flow', 'Triggering safeties', 'Overfit edges'],
    complements: ['GT Counter', 'Bubble / Tunnel', '4 Verts'],
    teachingPoints: [
      'Best called after the defense has been forced to respect counter action.',
      'Do not carry this unless the base run is truly a threat.',
      'Use for explosives, not volume.',
    ],
  },
];

export const seedCalls = [
  {
    id: 'call-iz-doubles-bubble',
    conceptId: 'inside-zone',
    callName: 'Doubles Right Inside Zone Bubble',
    formation: 'Doubles',
    personnel: '10',
    tags: ['Bubble'],
    situations: ['base', 'first_and_ten'],
    notes: 'Conflict apex defender and steal free grass if numbers are soft.',
    weeklyDefault: true,
  },
  {
    id: 'call-iz-trips-slice',
    conceptId: 'inside-zone',
    callName: 'Trips Left Inside Zone Slice',
    formation: 'Trips',
    personnel: '11',
    tags: ['Slice'],
    situations: ['base', 'red_zone'],
    notes: 'Split-flow look to handle backside chase.',
    weeklyDefault: true,
  },
  {
    id: 'call-iz-pistol-read',
    conceptId: 'inside-zone',
    callName: 'Pistol Strong Inside Zone Read',
    formation: 'Pistol Strong',
    personnel: '11',
    tags: ['Read'],
    situations: ['first_and_ten', 'second_medium'],
    notes: 'Read the edge and remove an extra fitter from the run count.',
    weeklyDefault: true,
  },
  {
    id: 'call-oz-snug-jet',
    conceptId: 'outside-zone',
    callName: 'Snug Right Outside Zone Jet',
    formation: 'Snug',
    personnel: '11',
    motion: 'Jet',
    tags: ['Jet'],
    situations: ['base', 'first_and_ten', 'shot'],
    notes: 'Use motion to widen force and distort pursuit angles.',
  },
  {
    id: 'call-counter-doubles-jet',
    conceptId: 'gt-counter',
    callName: 'Doubles Left Jet GT Counter',
    formation: 'Doubles',
    personnel: '10',
    motion: 'Jet',
    tags: ['Jet'],
    situations: ['first_and_ten', 'shot'],
    notes: 'Good after multiple zone or jet presentations.',
    weeklyDefault: true,
  },
  {
    id: 'call-counter-trips-read',
    conceptId: 'gt-counter',
    callName: 'Trips Right GT Counter Read',
    formation: 'Trips',
    personnel: '11',
    tags: ['Read'],
    situations: ['base', 'third_short', 'red_zone'],
    notes: 'Edge read keeps the backside defender from folding inside.',
  },
  {
    id: 'call-powerread-pistol',
    conceptId: 'power-read',
    callName: 'Pistol Strong Power Read',
    formation: 'Pistol Strong',
    personnel: '11',
    tags: ['Read'],
    situations: ['goal_line', 'second_short'],
    notes: 'Good short-yardage answer with QB involvement.',
  },
  {
    id: 'call-stick-doubles',
    conceptId: 'stick',
    callName: 'Doubles Right Stick',
    formation: 'Doubles',
    personnel: '10',
    tags: [],
    situations: ['first_and_ten', 'third_short'],
    notes: 'Simple completion versus underneath zone structure.',
    weeklyDefault: true,
  },
  {
    id: 'call-stick-trips-now',
    conceptId: 'stick',
    callName: 'Trips Left Stick Now',
    formation: 'Trips',
    personnel: '10',
    tags: ['Now'],
    situations: ['base', 'pressure'],
    notes: 'Built-in fast access if the perimeter is free.',
  },
  {
    id: 'call-stick-empty-bubble',
    conceptId: 'stick',
    callName: 'Empty Stick Bubble',
    formation: 'Empty',
    personnel: 'empty',
    tags: ['Bubble'],
    situations: ['third_short', 'two_minute'],
    notes: 'Fast spacing answer with outlet built in.',
  },
  {
    id: 'call-slantarrow-doubles',
    conceptId: 'slant-arrow',
    callName: 'Doubles Right Slant Arrow',
    formation: 'Doubles',
    personnel: '10',
    tags: [],
    situations: ['first_and_ten', 'second_short', 'pressure'],
    notes: 'Take easy rhythm yards when corners are soft.',
    weeklyDefault: true,
  },
  {
    id: 'call-hitch-empty',
    conceptId: 'hitch',
    callName: 'Empty Hitch',
    formation: 'Empty',
    personnel: 'empty',
    tags: [],
    situations: ['backed_up', 'pressure'],
    notes: 'Quick answer to prevent the rush from getting home.',
  },
  {
    id: 'call-snag-bunch-wheel',
    conceptId: 'snag',
    callName: 'Bunch Right Snag Wheel',
    formation: 'Bunch',
    personnel: '11',
    tags: ['Wheel'],
    situations: ['third_short', 'red_zone'],
    notes: 'Good red-zone spacing with a vertical answer tagged in.',
    weeklyDefault: true,
  },
  {
    id: 'call-mesh-doubles',
    conceptId: 'mesh',
    callName: 'Doubles Mesh',
    formation: 'Doubles',
    personnel: '10',
    tags: [],
    situations: ['third_medium', 'two_minute'],
    notes: 'Chain-moving base version.',
    weeklyDefault: true,
  },
  {
    id: 'call-mesh-bunch-wheel',
    conceptId: 'mesh',
    callName: 'Bunch Left Mesh Wheel',
    formation: 'Bunch',
    personnel: '11',
    tags: ['Wheel'],
    situations: ['third_medium', 'red_zone'],
    notes: 'Great man answer with run-after-catch potential.',
  },
  {
    id: 'call-verts-trips-bender',
    conceptId: 'four-verts',
    callName: 'Trips Right 4 Verts Bender',
    formation: 'Trips',
    personnel: '10',
    tags: ['Bender'],
    situations: ['third_long', 'two_minute', 'shot'],
    notes: 'Attack the middle-open safety structure.',
    weeklyDefault: true,
  },
  {
    id: 'call-verts-empty-switch',
    conceptId: 'four-verts',
    callName: 'Empty 4 Verts Switch',
    formation: 'Empty',
    personnel: 'empty',
    tags: ['Switch'],
    situations: ['two_minute', 'third_long'],
    notes: 'Useful when the defense is matching routes aggressively.',
  },
  {
    id: 'call-cross-trips',
    conceptId: 'cross',
    callName: 'Trips Right Y Cross',
    formation: 'Trips',
    personnel: '11',
    tags: ['Half Slide'],
    situations: ['third_medium', 'third_long'],
    notes: 'Intermediate answer versus single-high spacing.',
    weeklyDefault: true,
  },
  {
    id: 'call-sail-doubles',
    conceptId: 'sail',
    callName: 'Doubles Left Sail',
    formation: 'Doubles',
    personnel: '10',
    tags: ['Half Slide'],
    situations: ['first_and_ten', 'second_medium'],
    notes: 'Attack cover-3 spacing on the sideline flood.',
    weeklyDefault: true,
  },
  {
    id: 'call-smash-trips',
    conceptId: 'smash',
    callName: 'Trips Right Smash',
    formation: 'Trips',
    personnel: '10',
    tags: [],
    situations: ['red_zone', 'third_short'],
    notes: 'Strong versus cloud or squat corners.',
  },
  {
    id: 'call-digmills-doubles',
    conceptId: 'dig-mills',
    callName: 'Doubles Mills',
    formation: 'Doubles',
    personnel: '10',
    tags: ['Half Slide'],
    situations: ['shot', 'third_long'],
    notes: 'Hold the middle safety and drive the dig behind him.',
  },
  {
    id: 'call-bubble-trips',
    conceptId: 'bubble-tunnel',
    callName: 'Trips Left Bubble',
    formation: 'Trips',
    personnel: '10',
    tags: ['Bubble'],
    situations: ['base', 'backed_up', 'pressure'],
    notes: 'Take free perimeter numbers.',
    weeklyDefault: true,
  },
  {
    id: 'call-tunnel-trips-open',
    conceptId: 'bubble-tunnel',
    callName: 'Trips Open Tunnel',
    formation: 'Trips Open',
    personnel: '10',
    tags: [],
    situations: ['first_and_ten', 'pressure'],
    notes: 'Useful when corners widen with bubble leverage.',
  },
  {
    id: 'call-middle-screen-doubles',
    conceptId: 'middle-screen',
    callName: 'Doubles Middle Screen',
    formation: 'Doubles',
    personnel: '10',
    tags: ['Half Slide'],
    situations: ['second_long', 'third_long', 'pressure'],
    notes: 'Good answer to interior rush lanes.',
  },
  {
    id: 'call-shuffle-pistol',
    conceptId: 'shuffle-screen',
    callName: 'Pistol Strong Shuffle Screen',
    formation: 'Pistol Strong',
    personnel: '11',
    motion: 'Orbit',
    tags: ['Half Slide'],
    situations: ['third_long', 'pressure'],
    notes: 'Punish edge rush after repeated dropback looks.',
  },
  {
    id: 'call-boot-doubles-slice',
    conceptId: 'boot-flood',
    callName: 'Doubles Right Boot Flood Slice',
    formation: 'Doubles',
    personnel: '11',
    tags: ['Slice', 'Half Slide'],
    situations: ['first_and_ten', 'shot', 'red_zone'],
    notes: 'Pair directly off split-flow zone action.',
    weeklyDefault: true,
  },
  {
    id: 'call-boot-snug-jet',
    conceptId: 'boot-flood',
    callName: 'Snug Left Boot Flood Jet',
    formation: 'Snug',
    personnel: '11',
    motion: 'Jet',
    tags: ['Jet'],
    situations: ['second_short', 'shot'],
    notes: 'Good tendency breaker after edge run action.',
  },
  {
    id: 'call-counterpass-trips',
    conceptId: 'counter-pass',
    callName: 'Trips Right Counter Pass',
    formation: 'Trips',
    personnel: '11',
    motion: 'Jet',
    tags: ['Half Slide'],
    situations: ['shot', 'red_zone'],
    notes: 'Explosive call after the defense starts triggering downhill.',
  },
];

export const seedPlayLibrary = {
  formations: seedFormations,
  tags: seedTags,
  concepts: seedConcepts,
  calls: seedCalls,
};

export function getSeedPlayLibrary() {
  return seedPlayLibrary;
}

export function getConceptsByTier(tier) {
  return seedConcepts.filter((c) => c.installTier === tier);
}

export function getConceptsByFamily(family) {
  return seedConcepts.filter((c) => c.family === family);
}

export function getConceptsForSituation(situation) {
  return seedConcepts.filter((c) => c.situations.includes(situation));
}

export function getCallsForConcept(conceptId) {
  return seedCalls.filter((c) => c.conceptId === conceptId);
}

export function getCallsForSituation(situation) {
  return seedCalls.filter((c) => c.situations.includes(situation));
}

export function getCoreConcepts() {
  return seedConcepts.filter((c) => c.core);
}

export function getWeeklyDefaultCalls() {
  return seedCalls.filter((c) => c.weeklyDefault);
}